CREATE TABLE loan_products (
    id UUID PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    currency_scale INTEGER NOT NULL CHECK (currency_scale BETWEEN 0 AND 4),
    min_amount NUMERIC(19,4) NOT NULL CHECK (min_amount > 0),
    max_amount NUMERIC(19,4) NOT NULL CHECK (max_amount >= min_amount),
    min_term_months INTEGER NOT NULL CHECK (min_term_months >= 1),
    max_term_months INTEGER NOT NULL CHECK (max_term_months >= min_term_months AND max_term_months <= 1200),
    annual_interest_rate NUMERIC(9,6) NOT NULL CHECK (annual_interest_rate BETWEEN 0 AND 100),
    max_debt_to_income_ratio NUMERIC(7,6) NOT NULL CHECK (max_debt_to_income_ratio > 0 AND max_debt_to_income_ratio <= 1),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL
);
CREATE TABLE product_required_documents (
    product_id UUID NOT NULL REFERENCES loan_products(id),
    document_type VARCHAR(40) NOT NULL,
    PRIMARY KEY (product_id, document_type)
);
CREATE TABLE loan_applications (
    id UUID PRIMARY KEY,
    applicant_id VARCHAR(200) NOT NULL,
    idempotency_key UUID NOT NULL,
    product_id UUID NOT NULL REFERENCES loan_products(id),
    amount TEXT NOT NULL,
    term_months INTEGER NOT NULL CHECK (term_months BETWEEN 1 AND 1200),
    monthly_income TEXT NOT NULL,
    monthly_debt TEXT NOT NULL,
    purpose TEXT NOT NULL,
    status VARCHAR(32) NOT NULL CHECK (status IN ('DRAFT','SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','WITHDRAWN')),
    reviewer_id VARCHAR(200),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    UNIQUE (applicant_id, idempotency_key)
);
CREATE INDEX idx_loans_applicant_created ON loan_applications(applicant_id, created_at DESC, id DESC);
CREATE INDEX idx_loans_status_created ON loan_applications(status, created_at DESC, id DESC);
CREATE TABLE loan_documents (
    id UUID PRIMARY KEY,
    application_id UUID NOT NULL REFERENCES loan_applications(id),
    document_type VARCHAR(40) NOT NULL,
    media_type VARCHAR(80) NOT NULL,
    size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
    encrypted_content TEXT NOT NULL,
    status VARCHAR(32) NOT NULL CHECK (status IN ('PENDING','VERIFIED','REJECTED')),
    verification_note TEXT,
    verified_by VARCHAR(200),
    verified_at TIMESTAMP WITH TIME ZONE,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (application_id, document_type)
);
CREATE TABLE loan_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id UUID NOT NULL REFERENCES loan_applications(id),
    actor_id VARCHAR(200) NOT NULL,
    action VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    note TEXT,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_events_application_id ON loan_events(application_id, id);

